name: Test Windows Environment

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}\build
      shell: powershell

    - name: Configure CMake
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run:  cmake ${{github.workspace}}

    - name: Build
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Test
      shell: cmd
      working-directory: ${{github.workspace}}/build/app/kens/Debug
      run: kens-all-run-solution.exe

    - name: Test (Unreliable)
      shell: cmd
      working-directory: ${{github.workspace}}/build/app/kens/Debug
      run: kens-all-unreliable-run-solution.exe